---
- name: Copy hosts
  hosts: all
  gather_facts: false

  tasks:
    - name: Create nice /etc/hosts on all
      template:
        src: files/etc-hosts/etc-hosts.j2
        dest: /etc/hosts
        mode: '0644'
