---
- name: Add a local firewall file
  hosts: all
  gather_facts: false

  tasks:
    - name: Configure Firewall Service
      template:
        src: files/firewall/firewall-rules.sh.j2
        dest: /usr/local/bin/firewall-rules.sh
        mode: '0755'
      notify: Restart firewall service

    - name: Create systemd service unit for firewall
      copy:
        src: files/firewall/firewall.service
        dest: /etc/systemd/system/firewall.service
      notify: Reload systemd and restart firewall service

  handlers:
    - name: Restart firewall service
      systemd:
        name: "firewall"
        state: restarted

    - name: Reload systemd and restart firewall service
      systemd:
        name: "firewall"
        state: restarted
        daemon_reload: true
