---
- name: Setup Gateway
  hosts: gateway
  gather_facts: false

  tasks:
    - name: Install misc gateway packages
      apt:
        pkg:
          - apache2-utils

    - name: Install nginx
      apt:
        name: nginx
        state: latest

    - name: Remove nginx default site available
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    - name: Copy nginx config file
      template:
        src: files/kubesol-gw/nginx.j2
        dest: /etc/nginx/nginx.conf
      notify: restart nginx

    - name: Enable nginx
      service:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
