# this gets the kubeconfig file from controller_one
# and store it as .kubeconfig on localhost
---
- name: Get the kubeconfig file from controller_one
  hosts: controller_one
  gather_facts: false

  tasks:
    - name: Get the kubeconfig file
      fetch:
        src: /root/.kube/config
        dest: .kube/
        flat: true

- name: Store it as .kubeconfig on localhost
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Name check local .kubeconfig file
      shell:
        cmd: test -f .kubeconfig
      changed_when: none
      register: kubeconfig_exist
      failed_when: none

    - debug:
        msg: "Warning: a .kubeconfig already exists!"
      when: kubeconfig_exist

    - name: Create local .kubeconfig file
      shell:
        cmd: sed -e "s/127.0.0.1/{{ ext_dns_name }}/" .kube/config >.kubeconfig
        creates: .kubeconfig

    - name: Permissions on local .kubeconfig file
      file:
        path: .kubeconfig
        mode: "0600"

    - name: Running kubectl get nodes
      shell:
        cmd: kubectl get nodes
      environment:
        KUBECONFIG: .kubeconfig
      register: kubectl_get_nodes
      changed_when: none

    - debug:
        var: kubectl_get_nodes.stdout_lines
