---
- name: Setup certificate rotate on controllers
  hosts: controller_one, controller
  serial: 1
  gather_facts: false

  tasks:
    - name: Stop rke2-server
      systemd:
        name: rke2-server
        state: stopped

    - name: Rke2 certificate rotate
      shell:
        cmd: rke2 certificate rotate

    - name: start rke2-server
      systemd:
        name: rke2-server
        state: started

- name: Setup certificate rotate on workers
  hosts: worker
  serial: 1
  gather_facts: false

  tasks:
    - name: Restart rke2-agent
      systemd:
        name: rke2-agent
        state: restarted
