---
- name: cert-manager helm install
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    NS: "cert-manager"

  tasks:
    - name: Add cert-manager helm repository
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: https://charts.jetstack.io

    - include_tasks: tasks/namespace.yaml

    - name: Install cert-manager
      kubernetes.core.helm:
        name: cert-manager
        namespace: "{{ NS }}"
        chart_ref: jetstack/cert-manager
        chart_version: "{{ cert_manager_chart_version | default('') }}"
        values:
          crds:
            enabled: true
