---
- name: Longhorn helm install
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    NS: longhorn-system

  tasks:
    - name: Add chart repo
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: https://charts.longhorn.io

    - include_tasks: tasks/namespace.yaml

    - name: Install
      kubernetes.core.helm:
        name: longhorn
        namespace: "{{ NS }}"
        chart_ref: longhorn/longhorn
        chart_version: "{{ longhorn_chart_version | default('') }}"
