---
- name: Longhorn rf1 storage class
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Create longhorn-rf1 storageclass
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: longhorn-rf1
          parameters:
            numberOfReplicas: "1"
            dataLocality: strict-local
            dataEngine: v1
            disableRevisionCounter: "true"
            fromBackup: ""
            fsType: ext4
            staleReplicaTimeout: "30"
            unmapMarkSnapChainRemoved: ignored
          provisioner: driver.longhorn.io
          reclaimPolicy: Delete
          volumeBindingMode: Immediate
          allowVolumeExpansion: true

