---
- name: Install dummy
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    D: "/root/.kubesol"

  tasks:
    - name: Dummy template j2 -> yaml
      template:
        src: "files/dummy/{{ item }}.j2"
        dest: "{{ D }}/.{{ item }}.yaml"
      with_items:
        - dummy-ns
        - dummy-ing
        - dummy-issuer
        - dummy-svc
        - dummy-sts

    - name: Dummy apply yamls
      kubernetes.core.k8s:
        state: present
        src: "{{ D }}/.{{ item }}.yaml"
      with_items:
        - dummy-ns
        - dummy-ing
        - dummy-issuer
        - dummy-svc
        - dummy-sts
