---
- name: loki helm install
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    NS: "monitoring"

  tasks:
    - name: Add grafana helm repository
      kubernetes.core.helm_repository:
        name: grafana
        repo_url: https://grafana.github.io/helm-charts

    - include_tasks: tasks/namespace.yaml

    - name: Install loki
      kubernetes.core.helm:
        name: loki
        namespace: "{{ NS }}"
        chart_ref: grafana/loki
        chart_version: "{{ loki_chart_version | default('') }}"
        values_files:
          - files/loki/values.yaml

    - name: Install Promtail
      kubernetes.core.helm:
        name: promtail
        namespace: "{{ NS }}"
        chart_ref: grafana/promtail
        chart_version: "{{ promtail_chart_version | default('') }}"
        values_files:
          - files/loki/promtail.yaml
