---
- name: loki helm uninstall
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    NS: "monitoring"

  tasks:
    - name: Remove loki
      kubernetes.core.helm:
        name: loki
        namespace: "{{ NS }}"
        state: absent
        wait: true

    - name: Remove Promtail
      kubernetes.core.helm:
        name: promtail
        namespace: "{{ NS }}"
        state: absent
        wait: true
