---
- name: Install ArgoCD
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    NS: argocd
    iname: argocd

  tasks:
    - name: Argocd helm repo
      kubernetes.core.helm_repository:
        name: argo
        repo_url: https://argoproj.github.io/argo-helm

    - include_tasks: tasks/namespace.yaml
    - include_tasks: tasks/issuer.yaml

    - name: Argocd helm install
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo/argo-cd
        chart_version: "{{ argocd_chart_version | default('') }}"
        namespace: "{{ NS }}"
        values:
          global:
            domain: "argocd.{{ ext_dns_name }}"
          configs:
            params:
              server.insecure: true
          server:
            autoscaling:
              enabled: true
              minReplicas: 1
              maxReplicas: 2
            ingress:
              enabled: true
              ingressClassName: nginx
              annotations:
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
                cert-manager.io/issuer: "letsencrypt-argocd"
              extraTls:
                - hosts:
                  - "argocd.{{ ext_dns_name }}"
                  secretName: argocd-tls
          redis-ha:
            enabled: true
          controller:
            replicas: 1
          repoServer:
            autoscaling:
              enabled: true
              minReplicas: 1
              maxReplicas: 2
          applicationSet:
            replicas: 1
