---
- name: Add Trivy Grafana dashboard
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Add Trivy Grafana Dashboard
      kubernetes.core.k8s:
        state: present
        src: files/trivy/grafana-dashboard.yaml
