---
- name: Install Vertical Pod Autoscaler VPA
  hosts: controller_one
  gather_facts: false

  tasks:
    - name: Get deploy_vpa
      shell:
        cmd: kubectl -n kube-system get deploy -o name | grep vpa-
      register: deploy_vpa
      changed_when: deploy_vpa.stdout != ""
      ignore_errors: true

    - pause:
        prompt: "It seems like it's already installed. Press ENTER to continue install/upgrade or CTRL+C,A to abort"
      when: deploy_vpa.stdout != ""

    - name: Autoscaler git checkout
      ansible.builtin.git:
        repo: "https://github.com/kubernetes/autoscaler.git"
        dest: /root/vpa

    - name: Run vpa-up.sh
      shell:
        chdir: /root/vpa/vertical-pod-autoscaler
        cmd: hack/vpa-up.sh
