---
- name: Install Goldilocks VPA
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    NS: "goldilocks"

  tasks:
    - name: Add fairwinds-stable helm repository
      kubernetes.core.helm_repository:
        name: fairwinds-stable
        repo_url: https://charts.fairwinds.com/stable

    - include_tasks: tasks/namespace.yaml

    - name: Install Goldilocks
      kubernetes.core.helm:
        name: goldilocks
        namespace: "{{ NS }}"
        chart_ref: fairwinds-stable/goldilocks

    - debug:
        msg: "Goldilocks and VPA are ready. Read kubesol documentation on usage."

